### ISSUE TITLE
Phishing

### ISSUE THREAD

**Issue by baxterclements** [baxterclements/Capstone#4]
- Outline topics.
- Write the lessons to provide a comprehensive student learning experience.
- Create or attach a variety of assessments to the lessons.
- add questions for the teacher to ask in order to drive home the lesson.

**Comment by ChampATW** [comment]
Done

**Comment by ChampATW** [comment]
I had little to no issue with completing this curriculum. After finding some good sources on phishing I was able to extract relevant information into a easily digestible format.
